"""add_municipality_to_dynamic_points

Revision ID: 06f7951b5ec3
Revises: 39e116d7d02d
Create Date: 2026-04-30 21:10:19.777365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '06f7951b5ec3'
down_revision: Union[str, None] = '39e116d7d02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_points', sa.Column('municipality', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dynamic_points', 'municipality')
    # ### end Alembic commands ###
