"""Init Schema

Revision ID: 39e116d7d02d
Revises: 
Create Date: 2026-04-29 03:53:39.662031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '39e116d7d02d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phases_id'), 'phases', ['id'], unique=False)
    op.create_index(op.f('ix_phases_name'), 'phases', ['name'], unique=True)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('municipality', sa.String(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='GEOMETRY', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_building_id'), 'buildings', ['building_id'], unique=False)
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_table('dynamic_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_points_id'), 'dynamic_points', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dynamic_points_id'), table_name='dynamic_points')
    op.drop_index('idx_dynamic_points_geom', table_name='dynamic_points', postgresql_using='gist')
    op.drop_table('dynamic_points')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_building_id'), table_name='buildings')
    op.drop_index('idx_buildings_geom', table_name='buildings', postgresql_using='gist')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_phases_name'), table_name='phases')
    op.drop_index(op.f('ix_phases_id'), table_name='phases')
    op.drop_table('phases')
    # ### end Alembic commands ###
