"""add_visual_distortion_reports

Revision ID: 61ff1794301f
Revises: e770c2cd71d5
Create Date: 2026-05-08 15:34:07.788790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '61ff1794301f'
down_revision: Union[str, None] = 'e770c2cd71d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_distortion_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality', sa.String(), nullable=True),
    sa.Column('report_number', sa.String(), nullable=True),
    sa.Column('visit_number', sa.String(), nullable=True),
    sa.Column('report_status', sa.String(), nullable=True),
    sa.Column('visit_status', sa.String(), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=True),
    sa.Column('assignment_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('classification_name', sa.String(), nullable=True),
    sa.Column('closing_status', sa.String(), nullable=True),
    sa.Column('last_observation_date', sa.DateTime(), nullable=True),
    sa.Column('first_observation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_distortion_reports_classification_name'), 'visual_distortion_reports', ['classification_name'], unique=False)
    op.create_index(op.f('ix_visual_distortion_reports_closing_status'), 'visual_distortion_reports', ['closing_status'], unique=False)
    op.create_index(op.f('ix_visual_distortion_reports_id'), 'visual_distortion_reports', ['id'], unique=False)
    op.create_index(op.f('ix_visual_distortion_reports_municipality'), 'visual_distortion_reports', ['municipality'], unique=False)
    op.create_index(op.f('ix_visual_distortion_reports_report_number'), 'visual_distortion_reports', ['report_number'], unique=True)
    op.create_index(op.f('ix_visual_distortion_reports_report_status'), 'visual_distortion_reports', ['report_status'], unique=False)
    op.create_index(op.f('ix_visual_distortion_reports_visit_number'), 'visual_distortion_reports', ['visit_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_distortion_reports_visit_number'), table_name='visual_distortion_reports')
    op.drop_index(op.f('ix_visual_distortion_reports_report_status'), table_name='visual_distortion_reports')
    op.drop_index(op.f('ix_visual_distortion_reports_report_number'), table_name='visual_distortion_reports')
    op.drop_index(op.f('ix_visual_distortion_reports_municipality'), table_name='visual_distortion_reports')
    op.drop_index(op.f('ix_visual_distortion_reports_id'), table_name='visual_distortion_reports')
    op.drop_index(op.f('ix_visual_distortion_reports_closing_status'), table_name='visual_distortion_reports')
    op.drop_index(op.f('ix_visual_distortion_reports_classification_name'), table_name='visual_distortion_reports')
    op.drop_index('idx_visual_distortion_reports_geom', table_name='visual_distortion_reports', postgresql_using='gist')
    op.drop_table('visual_distortion_reports')
    # ### end Alembic commands ###
