"""migrate_to_schemas

Revision ID: aa66f82870ac
Revises: 61ff1794301f
Create Date: 2026-05-08 15:56:23.159929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'aa66f82870ac'
down_revision: Union[str, None] = '61ff1794301f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buildings_building_id'), table_name='buildings', schema='compliance')
    op.drop_index(op.f('ix_buildings_district'), table_name='buildings', schema='compliance')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings', schema='compliance')
    op.drop_index(op.f('ix_buildings_is_compliant'), table_name='buildings', schema='compliance')
    op.drop_index(op.f('ix_buildings_municipality'), table_name='buildings', schema='compliance')
    op.drop_index(op.f('ix_buildings_street'), table_name='buildings', schema='compliance')
    op.create_index(op.f('ix_compliance_buildings_building_id'), 'buildings', ['building_id'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_buildings_district'), 'buildings', ['district'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_buildings_id'), 'buildings', ['id'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_buildings_is_compliant'), 'buildings', ['is_compliant'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_buildings_municipality'), 'buildings', ['municipality'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_buildings_street'), 'buildings', ['street'], unique=False, schema='compliance')
    op.drop_index(op.f('ix_dynamic_points_district'), table_name='dynamic_points', schema='compliance')
    op.drop_index(op.f('ix_dynamic_points_id'), table_name='dynamic_points', schema='compliance')
    op.drop_index(op.f('ix_dynamic_points_municipality'), table_name='dynamic_points', schema='compliance')
    op.drop_index(op.f('ix_dynamic_points_street'), table_name='dynamic_points', schema='compliance')
    op.create_index(op.f('ix_compliance_dynamic_points_district'), 'dynamic_points', ['district'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_dynamic_points_id'), 'dynamic_points', ['id'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_dynamic_points_municipality'), 'dynamic_points', ['municipality'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_dynamic_points_street'), 'dynamic_points', ['street'], unique=False, schema='compliance')
    op.drop_index(op.f('ix_phases_id'), table_name='phases', schema='compliance')
    op.drop_index(op.f('ix_phases_name'), table_name='phases', schema='compliance')
    op.create_index(op.f('ix_compliance_phases_id'), 'phases', ['id'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_phases_name'), 'phases', ['name'], unique=True, schema='compliance')
    op.drop_index(op.f('ix_roads_id'), table_name='roads', schema='compliance')
    op.drop_index(op.f('ix_roads_municipality'), table_name='roads', schema='compliance')
    op.drop_index(op.f('ix_roads_name'), table_name='roads', schema='compliance')
    op.drop_index(op.f('ix_roads_road_id'), table_name='roads', schema='compliance')
    op.create_index(op.f('ix_compliance_roads_id'), 'roads', ['id'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_roads_municipality'), 'roads', ['municipality'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_roads_name'), 'roads', ['name'], unique=False, schema='compliance')
    op.create_index(op.f('ix_compliance_roads_road_id'), 'roads', ['road_id'], unique=False, schema='compliance')
    op.drop_index(op.f('ix_visual_distortion_reports_classification_name'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_reports_closing_status'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_reports_id'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_reports_municipality'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_reports_report_number'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_reports_report_status'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_reports_visit_number'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_visual_distortion_reports_classification_name'), 'visual_distortion_reports', ['classification_name'], unique=False, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_visual_distortion_reports_closing_status'), 'visual_distortion_reports', ['closing_status'], unique=False, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_visual_distortion_reports_id'), 'visual_distortion_reports', ['id'], unique=False, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_visual_distortion_reports_municipality'), 'visual_distortion_reports', ['municipality'], unique=False, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_visual_distortion_reports_report_number'), 'visual_distortion_reports', ['report_number'], unique=True, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_visual_distortion_reports_report_status'), 'visual_distortion_reports', ['report_status'], unique=False, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_visual_distortion_reports_visit_number'), 'visual_distortion_reports', ['visit_number'], unique=False, schema='visual_distortion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_distortion_visual_distortion_reports_visit_number'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_visual_distortion_reports_report_status'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_visual_distortion_reports_report_number'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_visual_distortion_reports_municipality'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_visual_distortion_reports_id'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_visual_distortion_reports_closing_status'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.drop_index(op.f('ix_visual_distortion_visual_distortion_reports_classification_name'), table_name='visual_distortion_reports', schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_reports_visit_number'), 'visual_distortion_reports', ['visit_number'], unique=False, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_reports_report_status'), 'visual_distortion_reports', ['report_status'], unique=False, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_reports_report_number'), 'visual_distortion_reports', ['report_number'], unique=True, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_reports_municipality'), 'visual_distortion_reports', ['municipality'], unique=False, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_reports_id'), 'visual_distortion_reports', ['id'], unique=False, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_reports_closing_status'), 'visual_distortion_reports', ['closing_status'], unique=False, schema='visual_distortion')
    op.create_index(op.f('ix_visual_distortion_reports_classification_name'), 'visual_distortion_reports', ['classification_name'], unique=False, schema='visual_distortion')
    op.drop_index(op.f('ix_compliance_roads_road_id'), table_name='roads', schema='compliance')
    op.drop_index(op.f('ix_compliance_roads_name'), table_name='roads', schema='compliance')
    op.drop_index(op.f('ix_compliance_roads_municipality'), table_name='roads', schema='compliance')
    op.drop_index(op.f('ix_compliance_roads_id'), table_name='roads', schema='compliance')
    op.create_index(op.f('ix_roads_road_id'), 'roads', ['road_id'], unique=False, schema='compliance')
    op.create_index(op.f('ix_roads_name'), 'roads', ['name'], unique=False, schema='compliance')
    op.create_index(op.f('ix_roads_municipality'), 'roads', ['municipality'], unique=False, schema='compliance')
    op.create_index(op.f('ix_roads_id'), 'roads', ['id'], unique=False, schema='compliance')
    op.drop_index(op.f('ix_compliance_phases_name'), table_name='phases', schema='compliance')
    op.drop_index(op.f('ix_compliance_phases_id'), table_name='phases', schema='compliance')
    op.create_index(op.f('ix_phases_name'), 'phases', ['name'], unique=True, schema='compliance')
    op.create_index(op.f('ix_phases_id'), 'phases', ['id'], unique=False, schema='compliance')
    op.drop_index(op.f('ix_compliance_dynamic_points_street'), table_name='dynamic_points', schema='compliance')
    op.drop_index(op.f('ix_compliance_dynamic_points_municipality'), table_name='dynamic_points', schema='compliance')
    op.drop_index(op.f('ix_compliance_dynamic_points_id'), table_name='dynamic_points', schema='compliance')
    op.drop_index(op.f('ix_compliance_dynamic_points_district'), table_name='dynamic_points', schema='compliance')
    op.create_index(op.f('ix_dynamic_points_street'), 'dynamic_points', ['street'], unique=False, schema='compliance')
    op.create_index(op.f('ix_dynamic_points_municipality'), 'dynamic_points', ['municipality'], unique=False, schema='compliance')
    op.create_index(op.f('ix_dynamic_points_id'), 'dynamic_points', ['id'], unique=False, schema='compliance')
    op.create_index(op.f('ix_dynamic_points_district'), 'dynamic_points', ['district'], unique=False, schema='compliance')
    op.drop_index(op.f('ix_compliance_buildings_street'), table_name='buildings', schema='compliance')
    op.drop_index(op.f('ix_compliance_buildings_municipality'), table_name='buildings', schema='compliance')
    op.drop_index(op.f('ix_compliance_buildings_is_compliant'), table_name='buildings', schema='compliance')
    op.drop_index(op.f('ix_compliance_buildings_id'), table_name='buildings', schema='compliance')
    op.drop_index(op.f('ix_compliance_buildings_district'), table_name='buildings', schema='compliance')
    op.drop_index(op.f('ix_compliance_buildings_building_id'), table_name='buildings', schema='compliance')
    op.create_index(op.f('ix_buildings_street'), 'buildings', ['street'], unique=False, schema='compliance')
    op.create_index(op.f('ix_buildings_municipality'), 'buildings', ['municipality'], unique=False, schema='compliance')
    op.create_index(op.f('ix_buildings_is_compliant'), 'buildings', ['is_compliant'], unique=False, schema='compliance')
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False, schema='compliance')
    op.create_index(op.f('ix_buildings_district'), 'buildings', ['district'], unique=False, schema='compliance')
    op.create_index(op.f('ix_buildings_building_id'), 'buildings', ['building_id'], unique=False, schema='compliance')
    # ### end Alembic commands ###
