"""verify_modular_structure

Revision ID: e770c2cd71d5
Revises: 06f7951b5ec3
Create Date: 2026-05-08 05:13:29.534717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e770c2cd71d5'
down_revision: Union[str, None] = '06f7951b5ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('street', sa.String(), nullable=True))
    op.add_column('buildings', sa.Column('district', sa.String(), nullable=True))
    op.drop_index(op.f('idx_buildings_geom_gist'), table_name='buildings', postgresql_using='gist')
    op.drop_index(op.f('idx_buildings_is_compliant'), table_name='buildings')
    op.create_index(op.f('ix_buildings_district'), 'buildings', ['district'], unique=False)
    op.create_index(op.f('ix_buildings_is_compliant'), 'buildings', ['is_compliant'], unique=False)
    op.create_index(op.f('ix_buildings_municipality'), 'buildings', ['municipality'], unique=False)
    op.create_index(op.f('ix_buildings_street'), 'buildings', ['street'], unique=False)
    op.drop_index(op.f('idx_points_geom_gist'), table_name='dynamic_points', postgresql_using='gist')
    op.create_index(op.f('ix_dynamic_points_district'), 'dynamic_points', ['district'], unique=False)
    op.create_index(op.f('ix_dynamic_points_municipality'), 'dynamic_points', ['municipality'], unique=False)
    op.create_index(op.f('ix_dynamic_points_street'), 'dynamic_points', ['street'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dynamic_points_street'), table_name='dynamic_points')
    op.drop_index(op.f('ix_dynamic_points_municipality'), table_name='dynamic_points')
    op.drop_index(op.f('ix_dynamic_points_district'), table_name='dynamic_points')
    op.create_index(op.f('idx_points_geom_gist'), 'dynamic_points', ['geom'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_buildings_street'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_municipality'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_is_compliant'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_district'), table_name='buildings')
    op.create_index(op.f('idx_buildings_is_compliant'), 'buildings', ['is_compliant'], unique=False)
    op.create_index(op.f('idx_buildings_geom_gist'), 'buildings', ['geom'], unique=False, postgresql_using='gist')
    op.drop_column('buildings', 'district')
    op.drop_column('buildings', 'street')
    # ### end Alembic commands ###
